#myrobot:
# Publish all joint states -----------------------------------
#  joint_state_controller:
#    type: joint_state_controller/JointStateController
#    publish_rate: 50
# Position Controllers ---------------------------------------
position_group_controller:
  type: position_controllers/JointGroupPositionController
  joints: 
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
