arm_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  gains:
    shoulder_pan_joint: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    shoulder_lift_joint: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    elbow_joint: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    wrist_1_joint: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    wrist_2_joint: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
    wrist_3_joint: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}

#arm_controller:
#  type: velocity_controllers/JointTrajectoryController
#  joints:
#    - panda_joint1
#    - panda_joint2
#    - panda_joint3
#    - panda_joint4
#    - panda_joint5
#    - panda_joint6
#    - panda_joint7
#  constraints:
#      goal_time: 0.6
#      stopped_velocity_tolerance: 0.05
#      panda_joint1: {trajectory: 0.1, goal: 0.1}
#      panda_joint2: {trajectory: 0.1, goal: 0.1}
#      panda_joint3: {trajectory: 0.1, goal: 0.1}
#      panda_joint4: {trajectory: 0.1, goal: 0.1}
#      panda_joint5: {trajectory: 0.1, goal: 0.1}
#      panda_joint6: {trajectory: 0.1, goal: 0.1}
#      panda_joint7: {trajectory: 0.1, goal: 0.1}
#  stop_trajectory_duration: 0.5
#  state_publish_rate:  25
#  action_monitor_rate: 10
#gripper_controller:
#  type: velocity_controllers/JointTrajectoryController
#  joints:
#    - panda_finger_joint1
#    - panda_finger_joint2
# 
#  constraints:
#      goal_time: 0.6
#      stopped_velocity_tolerance: 0.05
#      panda_finger_joint1: {trajectory: 0.1, goal: 0.1}
#      panda_finger_joint2: {trajectory: 0.1, goal: 0.1}
#  stop_trajectory_duration: 0.5
#  state_publish_rate:  25
#  action_monitor_rate: 10
  




